name: zikanri
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  share: ^0.6.3+6
  intl: ^0.16.1
  provider: ^4.0.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  esys_flutter_share: ^1.0.2
  vibration: ^1.2.4
  flutter_circular_chart: ^0.1.0
  flutter_swiper : ^1.1.6
  introduction_screen: ^1.0.8
  cupertino_icons: ^0.1.2

dependency_overrides:
  dartx: ^0.3.0

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
      - asset: fonts/NotoSansJP-Bold.otf
        weight: 700
      - asset: fonts/NotoSansJP-Regular.otf
        weight: 400
      - asset: fonts/NotoSansJP-Thin.otf
        weight: 100
  assets:
    - images/zikanri_shaped.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/5.png